schema_version = "1.0.0"

id = "BTMG"
version = "1.0.0"
name = "Bone To Mesh Gen"
tagline = "Convert armature bones to mesh objects"
maintainer = "MaGr"

type = "add-on"

# Only keeping essential fields
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

tags = [ "Mesh", "Rigging"]

description = """
A addon to convert blender armatures to mesh. The transformed mesh is weighted with the armature.
"""
